#!/usr/bin/env python

import argparse
import logging
import sys
import pprint

sys.path.append('.')

import inti.client
import inti.frontend

__description__ = 'Inti CLI frontend'

_d_debug = False
_d_api = 'http://localhost:7231'

ll2str = {
    10: 'DEBUG',
    20: 'INFO',
    30: 'WARNING',
    40: 'ERROR',
    50: 'CRITICAL'
}


def main():
    parser = argparse.ArgumentParser(description=__description__)
    parser.add_argument('-D', dest='debug', action='store_true',
        default=_d_debug, help='Enable debugging')
    parser.add_argument('-l', dest='api', action='store', type=str,
        default=_d_api, help='Api to connect to')

    args = parser.parse_args()

    logger = logging.getLogger('main')
    if args.debug:
        log_level = logging.DEBUG
    else:
        log_level = logging.INFO
    logger.setLevel(log_level)

    console_logger = logging.StreamHandler()
    console_logger.setLevel(log_level)
    formatter = logging.Formatter('%(asctime)s [%(levelname)s]: %(message)s')
    console_logger.setFormatter(formatter)
    logger.addHandler(console_logger)

    logger.debug('logging at %s' % ll2str[log_level])

    api = inti.client.ApiClient(args.api)

    frontend = inti.frontend.NcursesFrontend(logger, api)
    frontend.run()

    return

if __name__ == '__main__':
    sys.exit(main())
